import { React } from "react";
import HomestoryLogo from "./media/homestorylogo.svg";
import StillhavenLogo from "./media/stillhavenlogo.svg";
import MLSlogo from "./media/mlslogo.png"

const ContactFooter = () => {
    return (
        <div className="component-container">
            <div className="contact-footer-top">
                <div>
                    <img src={HomestoryLogo} alt="homestory logo"/>
                    <p>778 887 2018</p>
                    <p>esther@yourhomestory.ca</p>
                </div>
                <div>  
                    <img src={StillhavenLogo} className="inverted-logo" alt="stillhaven logo"/>
                    <p>Stilhavn Real Estate Services</p>
                    <p>36 E 5th Ave, Vancouver, BC V5T 1G8</p>
                </div>
              
            </div>
            <div className="contact-footer-bottom">
                <p>The data relating to real estate on this web site comes in part from the MLS® Reciprocity program of the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board. Real estate listings held by participating real estate firms are marked with the MLS® Reciprocity logo and detailed information about the listing includes the name of the listing agent. This representation is based in whole or part on data generated by the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board which assumes no responsibility for its accuracy. The materials contained on this page may not be reproduced without the express written consent of the Real Estate Board of Greater Vancouver or the Fraser Valley Real Estate Board.</p>
                <img src={MLSlogo} alt="MLS logo"/>
              </div>
        </div>
    )
}

export default ContactFooter;